apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: name1
spec:
  containers:
    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    node: system
