apiVersion: v1
kind: Pod
metadata:
  labels:
    app: service-db
    version: v1
  name: persona-bd
  namespace: name1
spec:
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
          - matchExpressions:
            - key: node
              operator: In
              values:
              - system
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - service-db
        topologyKey: "kubernetes.io/hostname"
  restartPolicy: OnFailure
  containers:
    - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: cm-db-persona
        - name: MYSQL_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_HOST
              name: cm-db-persona
      image: josue180610/mysql-persona:1.0.0
      name: bd
      ports:
        - containerPort: 3306

  
