apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-app-persona
    version: v1.0
  name: deploy-app-persona
  namespace: name2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-app-persona
      version: v1.0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy-app-persona
        version: v1.0
    spec:
      containers:
        - env:
            - name: host
              valueFrom:
                secretKeyRef:
                  key: DB_HOST_MYSQL
                  name: secret-app-persona
            - name: port
              valueFrom:
                secretKeyRef:
                  key: DB_PORT_MYSQL
                  name: secret-app-persona
            - name: username
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME_MYSQL
                  name: secret-app-persona
            - name: password
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD_MYSQL
                  name: secret-app-persona
            - name: database
              valueFrom:
                secretKeyRef:
                  key: DB_MYSQL
                  name: secret-app-persona
          image: josue180610/api-persona-app:1.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: app-persona
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 4
            successThreshold: 1
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 5
