apiVersion: v1
kind: Service
metadata:
  name: app-persona-balancer
  namespace: name2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name:  loadbalancer-app-persona
  selector:
    app: deploy-app-persona
